services:
  monorepo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - payflow_net
    env_file:
      - ./apps/web/.env
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "pnpm --filter web run prisma:migrate && pnpm run dev"
      
networks:
  payflow_net:
    driver: bridge