apiVersion: v2
name: payflow-chart
description: A Helm chart for deploying the Payflow monorepo application.
type: application
version: 0.1.0
appVersion: "0.0.1"

dependencies:
  - name: kube-prometheus-stack
    version: "75.4.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    alias: prometheus-stack
    condition: monitoring.enabled