replicaCount: 1

image:
  repository: localhost:5001/payflow
  pullPolicy: Always
  tag: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

migration:
  enabled: false

app:
  config:
    databaseUrl: ""
    googleClientId: ""
    googleClientSecret: ""
    nextauthSecret: ""
    nextauthUrl: ""
    upstashRedisRestUrl: ""
    upstashRedisRestToken: ""
    turnstileSecretKey: ""
    nextPublicTurnstileSiteKey: ""

monitoring:
  enabled: true

prometheus-stack: {}