apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "payflow-chart.fullname" . }}
  labels:
    {{- include "payflow-chart.labels" . | nindent 4 }}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "payflow-chart.fullname" . }}
                port:
                  number: {{ .Values.service.port }}