{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "payflow-chart.fullname" . }}-migration
  labels:
    {{- include "payflow-chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-migration"
      labels:
        {{- include "payflow-chart.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: prisma-migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["pnpm", "--filter", "web", "run", "prisma:migrate"] 
          envFrom:
            - secretRef:
                name: {{ include "payflow-chart.fullname" . }}
  backoffLimit: 1
{{- end }}