apiVersion: v1
kind: Secret
metadata:
  name: {{ include "payflow-chart.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.app.config.databaseUrl | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.app.config.googleClientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.app.config.googleClientSecret | quote }}
  NEXTAUTH_SECRET: {{ .Values.app.config.nextauthSecret | quote }}
  NEXTAUTH_URL: {{ .Values.app.config.nextauthUrl | quote }}
  UPSTASH_REDIS_REST_URL: {{ .Values.app.config.upstashRedisRestUrl | quote }}
  UPSTASH_REDIS_REST_TOKEN: {{ .Values.app.config.upstashRedisRestToken | quote }}
  TURNSTILE_SECRET_KEY: {{ .Values.app.config.turnstileSecretKey | quote }}
  NEXT_PUBLIC_TURNSTILE_SITE_KEY: {{ .Values.app.config.nextPublicTurnstileSiteKey | quote }}