name: payFlow CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "apps/web/**"
      - "packages/ui/**"
      - "pnpm-lock.yaml"
      - "package.json"
      - "turbo.json"
      - ".github/workflows/ci.yml"

jobs:
  validate-web-app:
    name: Validate Web App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.8.1

      - name: Get pnpm Store Directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Setup pnpm Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Ensure Cypress Binary is Installed
        run: pnpm --filter=web exec cypress install

      - name: Prepare Test Database
        run: pnpm --filter=web run prisma:reset
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run Tests
        run: pnpm --filter=web run test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build Project
        run: pnpm build

      - name: Run Cypress E2E Tests on Staging
        uses: cypress-io/github-action@v6
        with:
          working-directory: apps/web
          install: false